apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: locust-master
  labels:
    app: locust-master
spec:
  type: NodePort
  ports:
    - port: 8089
      name: locust-master
      nodePort: 30001
  selector:
    app: locust-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: locust:local
          ports:
            - containerPort: 8089
          args: ["--host", "http://gameserver:8080", "--master"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-slave
  labels:
    app: locust-slave
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-slave
  template:
    metadata:
      labels:
        app: locust-slave
    spec:
      containers:
        - name: locust-slave
          image: locust:local
          ports:
            - containerPort: 8089
          args: ["--host=http://gameserver:8080", "--slave", "--master-host=locust-master"]
